[package]
name = "rune-indexer-interface"
version = "0.1.0"
authors = ["kachinsky@oct.network"]
repository = "https://github.com/octopus-network/ord-canister"
license = "MIT"
edition = "2021"

[dependencies]
candid = "0.9"
thiserror = "1"
